server:
  port: 8888
spring:
  application:
    name: bugui
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AlessandroBartsch/cloud-config
          default-label: main
          search-paths:
            - 'greeting-service*'